export const BUTTON_VALUES = {
  A: 1,
  B: 2,
  Select: 4,
  Start: 8,
  Right: 16,
  Left: 32,
  Up: 64,
  Down: 128,
  R: 256,
  L: 512,
};

export const ADDRESS_LOOKUP = {
  item: {
    // starts at address: 0x0203BB20
    type: "203C224", // basically the tail for [type] [amount]
    amount: "203C226",
  },
  "key item": {
    // starts at address: 0x0203C228
    type: "203C350", // basically the tail for [type] [amount]
    amount: "203C352",
  },
  pokeball: {
    // starts at address: 0x0203C354
    type: "203C418",
    amount: "203C41A",
  },
  tm: {
    // starts at address: 0x0203C41C
    type: "203C618", // basically the tail for [type] [amount]
    amount: "203C61A",
  },
  berry: {
    // starts at address: 0x0203C61C
    type: "203C728", // basically the tail for [type] [amount]
    amount: "203C72A",
  },
};

export const MODE_OPTIONS = [
  {
    value: "pokeball",
    label: "Pokeballs",
    icon: "https://img.pokemondb.net/sprites/items/poke-ball.png",
  },
  {
    value: "key item",
    label: "Key Items",
    icon: "https://img.pokemondb.net/sprites/items/storage-key.png",
  },
  {
    value: "berry",
    label: "Berries",
    icon: "https://img.pokemondb.net/sprites/items/cheri-berry.png",
  },
  {
    value: "tm",
    label: "TMs",
    icon: "https://img.pokemondb.net/sprites/items/tm-normal.png",
  },
  {
    value: "item",
    label: "Items",
    icon: "https://img.pokemondb.net/sprites/items/potion.png",
  },
];

export const POKEBALL_ITEM_OPTIONS = [
  {
    value: 0x0001,
    label: "Master Ball",
    hex: "0x01",
    icon: "https://img.pokemondb.net/sprites/items/master-ball.png",
  },
  {
    value: 0x0002,
    label: "Ultra Ball",
    hex: "0x02",
    icon: "https://img.pokemondb.net/sprites/items/ultra-ball.png",
  },
  {
    value: 0x0003,
    label: "Great Ball",
    hex: "0x03",
    icon: "https://img.pokemondb.net/sprites/items/great-ball.png",
  },
  {
    value: 0x0004,
    label: "Pokeball",
    hex: "0x04",
    icon: "https://img.pokemondb.net/sprites/items/poke-ball.png",
  },
  {
    value: 0x0005,
    label: "Safari Ball",
    hex: "0x05",
    icon: "https://img.pokemondb.net/sprites/items/safari-ball.png",
  },
  {
    value: 0x0006,
    label: "Net Ball",
    hex: "0x06",
    icon: "https://img.pokemondb.net/sprites/items/net-ball.png",
  },
  {
    value: 0x0007,
    label: "Dive Ball",
    hex: "0x07",
    icon: "https://img.pokemondb.net/sprites/items/dive-ball.png",
  },
  {
    value: 0x0008,
    label: "Nest Ball",
    hex: "0x08",
    icon: "https://img.pokemondb.net/sprites/items/nest-ball.png",
  },
  {
    value: 0x0009,
    label: "Repeat Ball",
    hex: "0x09",
    icon: "https://img.pokemondb.net/sprites/items/repeat-ball.png",
  },
  {
    value: 0x000a,
    label: "Timer Ball",
    hex: "0x0A",
    icon: "https://img.pokemondb.net/sprites/items/timer-ball.png",
  },
  {
    value: 0x000b,
    label: "Luxury Ball",
    hex: "0x0B",
    icon: "https://img.pokemondb.net/sprites/items/luxury-ball.png",
  },
  {
    value: 0x000c,
    label: "Premier Ball",
    hex: "0x0C",
    icon: "https://img.pokemondb.net/sprites/items/premier-ball.png",
  },
  {
    value: 0x00ef,
    label: "Cherish Ball",
    hex: "0xEF",
    icon: "https://img.pokemondb.net/sprites/items/cherish-ball.png",
  },
  {
    value: 0x00f0,
    label: "Dusk Ball",
    hex: "0xF0",
    icon: "https://img.pokemondb.net/sprites/items/dusk-ball.png",
  },
  {
    value: 0x00f1,
    label: "Heal Ball",
    hex: "0xF1",
    icon: "https://img.pokemondb.net/sprites/items/heal-ball.png",
  },
  {
    value: 0x00f2,
    label: "Quick Ball",
    hex: "0xF2",
    icon: "https://img.pokemondb.net/sprites/items/quick-ball.png",
  },
  {
    value: 0x00f3,
    label: "Fast Ball",
    hex: "0xF3",
    icon: "https://img.pokemondb.net/sprites/items/fast-ball.png",
  },
  {
    value: 0x00f4,
    label: "Level Ball",
    hex: "0xF4",
    icon: "https://img.pokemondb.net/sprites/items/level-ball.png",
  },
  {
    value: 0x00f5,
    label: "Lure Ball",
    hex: "0xF5",
    icon: "https://img.pokemondb.net/sprites/items/lure-ball.png",
  },
  {
    value: 0x00f6,
    label: "Heavy Ball",
    hex: "0xF6",
    icon: "https://img.pokemondb.net/sprites/items/heavy-ball.png",
  },
  {
    value: 0x00f7,
    label: "Love Ball",
    hex: "0xF7",
    icon: "https://img.pokemondb.net/sprites/items/love-ball.png",
  },
  {
    value: 0x00f8,
    label: "Friend Ball",
    hex: "0xF8",
    icon: "https://img.pokemondb.net/sprites/items/friend-ball.png",
  },
  {
    value: 0x00f9,
    label: "Moon Ball",
    hex: "0xF9",
    icon: "https://img.pokemondb.net/sprites/items/moon-ball.png",
  },
  {
    value: 0x00fa,
    label: "Sport Ball",
    hex: "0xFA",
    icon: "https://img.pokemondb.net/sprites/items/sport-ball.png",
  },
  {
    value: 0x00fb,
    label: "Beast Ball",
    hex: "0xFB",
    icon: "https://img.pokemondb.net/sprites/items/beast-ball.png",
  },
  {
    value: 0x00fc,
    label: "Dream Ball",
    hex: "0xFC",
    icon: "https://img.pokemondb.net/sprites/items/dream-ball.png",
  },
  {
    value: 0x00fd,
    label: "Park Ball",
    hex: "0xFD",
    icon: "https://img.pokemondb.net/sprites/items/park-ball.png",
  },
];

export const ITEM_OPTIONS = [
  {
    value: 0x000d,
    label: "Potion",
    hex: "0x0D",
    icon: "https://img.pokemondb.net/sprites/items/potion.png",
  },
  {
    value: 0x000e,
    label: "Antidote",
    hex: "0x0E",
    icon: "https://img.pokemondb.net/sprites/items/antidote.png",
  },
  {
    value: 0x000f,
    label: "Burn Heal",
    hex: "0x0F",
    icon: "https://img.pokemondb.net/sprites/items/burn-heal.png",
  },
  {
    value: 0x0010,
    label: "Ice Heal",
    hex: "0x10",
    icon: "https://img.pokemondb.net/sprites/items/ice-heal.png",
  },
  {
    value: 0x0011,
    label: "Awakening",
    hex: "0x11",
    icon: "https://img.pokemondb.net/sprites/items/awakening.png",
  },
  {
    value: 0x0012,
    label: "Parlyz Heal",
    hex: "0x12",
    icon: "https://img.pokemondb.net/sprites/items/parlyz-heal.png",
  },
  {
    value: 0x0013,
    label: "Full Restore",
    hex: "0x13",
    icon: "https://img.pokemondb.net/sprites/items/full-restore.png",
  },
  {
    value: 0x0014,
    label: "Max Potion",
    hex: "0x14",
    icon: "https://img.pokemondb.net/sprites/items/max-potion.png",
  },
  {
    value: 0x0015,
    label: "Hyper Potion",
    hex: "0x15",
    icon: "https://img.pokemondb.net/sprites/items/hyper-potion.png",
  },
  {
    value: 0x0016,
    label: "Super Potion",
    hex: "0x16",
    icon: "https://img.pokemondb.net/sprites/items/super-potion.png",
  },
  {
    value: 0x0017,
    label: "Full Heal",
    hex: "0x17",
    icon: "https://img.pokemondb.net/sprites/items/full-heal.png",
  },
  {
    value: 0x0018,
    label: "Revive",
    hex: "0x18",
    icon: "https://img.pokemondb.net/sprites/items/revive.png",
  },
  {
    value: 0x0019,
    label: "Max Revive",
    hex: "0x19",
    icon: "https://img.pokemondb.net/sprites/items/max-revive.png",
  },
  {
    value: 0x001a,
    label: "Fresh Water",
    hex: "0x1A",
    icon: "https://img.pokemondb.net/sprites/items/fresh-water.png",
  },
  {
    value: 0x001b,
    label: "Soda Pop",
    hex: "0x1B",
    icon: "https://img.pokemondb.net/sprites/items/soda-pop.png",
  },
  {
    value: 0x001c,
    label: "Lemonade",
    hex: "0x1C",
    icon: "https://img.pokemondb.net/sprites/items/lemonade.png",
  },
  {
    value: 0x001d,
    label: "Moomoo Milk",
    hex: "0x1D",
    icon: "https://img.pokemondb.net/sprites/items/moomoo-milk.png",
  },
  {
    value: 0x001e,
    label: "Energy Powder",
    hex: "0x1E",
    icon: "https://img.pokemondb.net/sprites/items/energy-powder.png",
  },
  {
    value: 0x001f,
    label: "Energy Root",
    hex: "0x1F",
    icon: "https://img.pokemondb.net/sprites/items/energy-root.png",
  },
  {
    value: 0x0020,
    label: "Heal Powder",
    hex: "0x20",
    icon: "https://img.pokemondb.net/sprites/items/heal-powder.png",
  },
  {
    value: 0x0021,
    label: "Revival Herb",
    hex: "0x21",
    icon: "https://img.pokemondb.net/sprites/items/revival-herb.png",
  },
  {
    value: 0x0022,
    label: "Ether",
    hex: "0x22",
    icon: "https://img.pokemondb.net/sprites/items/ether.png",
  },
  {
    value: 0x0023,
    label: "Max Ether",
    hex: "0x23",
    icon: "https://img.pokemondb.net/sprites/items/max-ether.png",
  },
  {
    value: 0x0024,
    label: "Elixir",
    hex: "0x24",
    icon: "https://img.pokemondb.net/sprites/items/elixir.png",
  },
  {
    value: 0x0025,
    label: "Max Elixir",
    hex: "0x25",
    icon: "https://img.pokemondb.net/sprites/items/max-elixir.png",
  },
  {
    value: 0x0026,
    label: "Lava Cookie",
    hex: "0x26",
    icon: "https://img.pokemondb.net/sprites/items/lava-cookie.png",
  },
  {
    value: 0x0027,
    label: "Blue Flute",
    hex: "0x27",
    icon: "https://img.pokemondb.net/sprites/items/blue-flute.png",
  },
  {
    value: 0x0028,
    label: "Yellow Flute",
    hex: "0x28",
    icon: "https://img.pokemondb.net/sprites/items/yellow-flute.png",
  },
  {
    value: 0x0029,
    label: "Red Flute",
    hex: "0x29",
    icon: "https://img.pokemondb.net/sprites/items/red-flute.png",
  },
  {
    value: 0x002a,
    label: "Black Flute",
    hex: "0x2A",
    icon: "https://img.pokemondb.net/sprites/items/black-flute.png",
  },
  {
    value: 0x002b,
    label: "White Flute",
    hex: "0x2B",
    icon: "https://img.pokemondb.net/sprites/items/white-flute.png",
  },
  {
    value: 0x002c,
    label: "Berry Juice",
    hex: "0x2C",
    icon: "https://img.pokemondb.net/sprites/items/berry-juice.png",
  },
  {
    value: 0x002d,
    label: "Sacred Ash",
    hex: "0x2D",
    icon: "https://img.pokemondb.net/sprites/items/sacred-ash.png",
  },
  {
    value: 0x002e,
    label: "Shoal Salt",
    hex: "0x2E",
    icon: "https://img.pokemondb.net/sprites/items/shoal-salt.png",
  },
  {
    value: 0x002f,
    label: "Shoal Shell",
    hex: "0x2F",
    icon: "https://img.pokemondb.net/sprites/items/shoal-shell.png",
  },
  {
    value: 0x0030,
    label: "Red Shard",
    hex: "0x30",
    icon: "https://img.pokemondb.net/sprites/items/red-shard.png",
  },
  {
    value: 0x0031,
    label: "Blue Shard",
    hex: "0x31",
    icon: "https://img.pokemondb.net/sprites/items/blue-shard.png",
  },
  {
    value: 0x0032,
    label: "Yellow Shard",
    hex: "0x32",
    icon: "https://img.pokemondb.net/sprites/items/yellow-shard.png",
  },
  {
    value: 0x0033,
    label: "Green Shard",
    hex: "0x33",
    icon: "https://img.pokemondb.net/sprites/items/green-shard.png",
  },
  {
    value: 0x0034,
    label: "Rage Candy Bar",
    hex: "0x34",
    icon: "https://img.pokemondb.net/sprites/items/rage-candy-bar.png",
  },
  {
    value: 0x0035,
    label: "Old Gateau",
    hex: "0x35",
    icon: "https://img.pokemondb.net/sprites/items/old-gateau.png",
  },
  {
    value: 0x0036,
    label: "Castelia Cone",
    hex: "0x36",
    icon: "https://img.pokemondb.net/sprites/items/castelia-cone.png",
  },
  {
    value: 0x0037,
    label: "Dream Patch",
    hex: "0x37",
    icon: "https://img.pokemondb.net/sprites/items/dream-patch.png",
  },
  {
    value: 0x0038,
    label: "Shalour Sable",
    hex: "0x38",
    icon: "https://img.pokemondb.net/sprites/items/shalour-sable.png",
  },
  {
    value: 0x0039,
    label: "Health Wing",
    hex: "0x39",
    icon: "https://img.pokemondb.net/sprites/items/health-wing.png",
  },
  {
    value: 0x003a,
    label: "Muscle Wing",
    hex: "0x3A",
    icon: "https://img.pokemondb.net/sprites/items/muscle-wing.png",
  },
  {
    value: 0x003b,
    label: "Resist Wing",
    hex: "0x3B",
    icon: "https://img.pokemondb.net/sprites/items/resist-wing.png",
  },
  {
    value: 0x003c,
    label: "Genius Wing",
    hex: "0x3C",
    icon: "https://img.pokemondb.net/sprites/items/genius-wing.png",
  },
  {
    value: 0x003d,
    label: "Clever Wing",
    hex: "0x3D",
    icon: "https://img.pokemondb.net/sprites/items/clever-wing.png",
  },
  {
    value: 0x003e,
    label: "Swift Wing",
    hex: "0x3E",
    icon: "https://img.pokemondb.net/sprites/items/swift-wing.png",
  },
  {
    value: 0x003f,
    label: "HP Up",
    hex: "0x3F",
    icon: "https://img.pokemondb.net/sprites/items/hp-up.png",
  },
  {
    value: 0x0040,
    label: "Protein",
    hex: "0x40",
    icon: "https://img.pokemondb.net/sprites/items/protein.png",
  },
  {
    value: 0x0041,
    label: "Iron",
    hex: "0x41",
    icon: "https://img.pokemondb.net/sprites/items/iron.png",
  },
  {
    value: 0x0042,
    label: "Carbos",
    hex: "0x42",
    icon: "https://img.pokemondb.net/sprites/items/carbon.png",
  },
  {
    value: 0x0043,
    label: "Calcium",
    hex: "0x43",
    icon: "https://img.pokemondb.net/sprites/items/calcium.png",
  },
  {
    value: 0x0044,
    label: "Rare Candy",
    hex: "0x44",
    icon: "https://img.pokemondb.net/sprites/items/rare-candy.png",
  },
  {
    value: 0x0045,
    label: "PP Up",
    hex: "0x45",
    icon: "https://img.pokemondb.net/sprites/items/pp-up.png",
  },
  {
    value: 0x0046,
    label: "Zinc",
    hex: "0x46",
    icon: "https://img.pokemondb.net/sprites/items/zinc.png",
  },
  {
    value: 0x0047,
    label: "PP Max",
    hex: "0x47",
    icon: "https://img.pokemondb.net/sprites/items/pp-max.png",
  },
  {
    value: 0x0048,
    label: "Ability Pill",
    hex: "0x48",
    icon: "https://img.pokemondb.net/sprites/items/ability-pill.png",
  },
  {
    value: 0x0049,
    label: "Guard Spec.",
    hex: "0x49",
    icon: "https://img.pokemondb.net/sprites/items/guard-spec.png",
  },
  {
    value: 0x004a,
    label: "Dire Hit",
    hex: "0x4A",
    icon: "https://img.pokemondb.net/sprites/items/dire-hit.png",
  },
  {
    value: 0x004b,
    label: "X Attack",
    hex: "0x4B",
    icon: "https://img.pokemondb.net/sprites/items/x-attack.png",
  },
  {
    value: 0x004c,
    label: "X Defend",
    hex: "0x4C",
    icon: "https://img.pokemondb.net/sprites/items/x-defend.png",
  },
  {
    value: 0x004d,
    label: "X Speed",
    hex: "0x4D",
    icon: "https://img.pokemondb.net/sprites/items/x-speed.png",
  },
  {
    value: 0x004e,
    label: "X Accuracy",
    hex: "0x4E",
    icon: "https://img.pokemondb.net/sprites/items/x-accuracy.png",
  },
  {
    value: 0x004f,
    label: "X Special",
    hex: "0x4F",
    icon: "https://img.pokemondb.net/sprites/items/x-special.png",
  },
  {
    value: 0x0050,
    label: "Poké Doll",
    hex: "0x50",
    icon: "https://img.pokemondb.net/sprites/items/poke-doll.png",
  },
  {
    value: 0x0051,
    label: "Fluffy Tail",
    hex: "0x51",
    icon: "https://img.pokemondb.net/sprites/items/fluffy-tail.png",
  },
  {
    value: 0x0052,
    label: "Big Malasada",
    hex: "0x52",
    icon: "https://img.pokemondb.net/sprites/items/big-malasada.png",
  },
  {
    value: 0x0053,
    label: "Super Repel",
    hex: "0x53",
    icon: "https://img.pokemondb.net/sprites/items/super-repel.png",
  },
  {
    value: 0x0054,
    label: "Max Repel",
    hex: "0x54",
    icon: "https://img.pokemondb.net/sprites/items/max-repel.png",
  },
  {
    value: 0x0055,
    label: "Escape Rope",
    hex: "0x55",
    icon: "https://img.pokemondb.net/sprites/items/escape-rope.png",
  },
  {
    value: 0x0056,
    label: "Repel",
    hex: "0x56",
    icon: "https://img.pokemondb.net/sprites/items/repel.png",
  },
  {
    value: 0x0057,
    label: "Link Cable",
    hex: "0x57",
    icon: "https://img.pokemondb.net/sprites/items/linkp-cable.png",
  },
  {
    value: 0x0058,
    label: "Protector",
    hex: "0x58",
    icon: "https://img.pokemondb.net/sprites/items/protector.png",
  },
  {
    value: 0x0059,
    label: "Electirizer",
    hex: "0x59",
    icon: "https://img.pokemondb.net/sprites/items/electirizer.png",
  },
  {
    value: 0x005a,
    label: "Magmarizer",
    hex: "0x5A",
    icon: "https://img.pokemondb.net/sprites/items/magmarizer.png",
  },
  {
    value: 0x005b,
    label: "Dubious Disc",
    hex: "0x5B",
    icon: "https://img.pokemondb.net/sprites/items/dubious-disc.png",
  },
  {
    value: 0x005c,
    label: "Reaper Cloth",
    hex: "0x5C",
    icon: "https://img.pokemondb.net/sprites/items/reaper-cloth.png",
  },
  {
    value: 0x005d,
    label: "Sun Stone",
    hex: "0x5D",
    icon: "https://img.pokemondb.net/sprites/items/sun-stone.png",
  },
  {
    value: 0x005e,
    label: "Moon Stone",
    hex: "0x5E",
    icon: "https://img.pokemondb.net/sprites/items/moon-stone.png",
  },
  {
    value: 0x005f,
    label: "Fire Stone",
    hex: "0x5F",
    icon: "https://img.pokemondb.net/sprites/items/fire-stone.png",
  },
  {
    value: 0x0060,
    label: "Thunder Stone",
    hex: "0x60",
    icon: "https://img.pokemondb.net/sprites/items/thunder-stone.png",
  },
  {
    value: 0x0061,
    label: "Water Stone",
    hex: "0x61",
    icon: "https://img.pokemondb.net/sprites/items/water-stone.png",
  },
  {
    value: 0x0062,
    label: "Leaf Stone",
    hex: "0x62",
    icon: "https://img.pokemondb.net/sprites/items/leaf-stone.png",
  },
  {
    value: 0x0063,
    label: "Shiny Stone",
    hex: "0x63",
    icon: "https://img.pokemondb.net/sprites/items/shiny-stone.png",
  },
  {
    value: 0x0064,
    label: "Dusk Stone",
    hex: "0x64",
    icon: "https://img.pokemondb.net/sprites/items/dusk-stone.png",
  },
  {
    value: 0x0065,
    label: "Dawn Stone",
    hex: "0x65",
    icon: "https://img.pokemondb.net/sprites/items/dawn-stone.png",
  },
  {
    value: 0x0066,
    label: "Ice Stone",
    hex: "0x66",
    icon: "https://img.pokemondb.net/sprites/items/ice-stone.png",
  },
  {
    value: 0x0067,
    label: "Tiny Mushroom",
    hex: "0x67",
    icon: "https://img.pokemondb.net/sprites/items/tiny-mushroom.png",
  },
  {
    value: 0x0068,
    label: "Big Mushroom",
    hex: "0x68",
    icon: "https://img.pokemondb.net/sprites/items/big-mushroom.png",
  },
  {
    value: 0x0069,
    label: "Balm Mushroom",
    hex: "0x69",
    icon: "https://img.pokemondb.net/sprites/items/balm-mushroom.png",
  },
  {
    value: 0x006a,
    label: "Pearl",
    hex: "0x6A",
    icon: "https://img.pokemondb.net/sprites/items/pearl.png",
  },
  {
    value: 0x006b,
    label: "Big Pearl",
    hex: "0x6B",
    icon: "https://img.pokemondb.net/sprites/items/big-pearl.png",
  },
  {
    value: 0x006c,
    label: "Stardust",
    hex: "0x6C",
    icon: "https://img.pokemondb.net/sprites/items/stardust.png",
  },
  {
    value: 0x006d,
    label: "Star Piece",
    hex: "0x6D",
    icon: "https://img.pokemondb.net/sprites/items/star-piece.png",
  },
  {
    value: 0x006e,
    label: "Nugget",
    hex: "0x6E",
    icon: "https://img.pokemondb.net/sprites/items/nugget.png",
  },
  {
    value: 0x006f,
    label: "Heart Scale",
    hex: "0x6F",
    icon: "https://img.pokemondb.net/sprites/items/heart scale.png",
  },
  {
    value: 0x0070,
    label: "Rare Bone",
    hex: "0x70",
    icon: "https://img.pokemondb.net/sprites/items/rare-bone.png",
  },
  {
    value: 0x0071,
    label: "Pearl String",
    hex: "0x71",
    icon: "https://img.pokemondb.net/sprites/items/pearl-string.png",
  },
  {
    value: 0x0072,
    label: "Comet Shard",
    hex: "0x72",
    icon: "https://img.pokemondb.net/sprites/items/comet-shard.png",
  },
  {
    value: 0x0073,
    label: "Big Nugget",
    hex: "0x73",
    icon: "https://img.pokemondb.net/sprites/items/big-nugget.png",
  },
  {
    value: 0x0074,
    label: "Honey",
    hex: "0x74",
    icon: "https://img.pokemondb.net/sprites/items/honey.png",
  },
  {
    value: 0x0075,
    label: "Pretty Wing",
    hex: "0x75",
    icon: "https://img.pokemondb.net/sprites/items/pretty-wing.png",
  },
  {
    value: 0x0076,
    label: "Oval Stone",
    hex: "0x76",
    icon: "https://img.pokemondb.net/sprites/items/oval-stone.png",
  },
  {
    value: 0x0077,
    label: "Razor Claw",
    hex: "0x77",
    icon: "https://img.pokemondb.net/sprites/items/razor-claw.png",
  },
  {
    value: 0x0078,
    label: "Razor Fang",
    hex: "0x78",
    icon: "https://img.pokemondb.net/sprites/items/razor-fang.png",
  },
  {
    value: 0x0079,
    label: "Orange Mail",
    hex: "0x79",
    icon: "https://img.pokemondb.net/sprites/items/orange-mail.png",
  },
  {
    value: 0x007a,
    label: "Harbor Mail",
    hex: "0x7A",
    icon: "https://img.pokemondb.net/sprites/items/harbor-mail.png",
  },
  {
    value: 0x007b,
    label: "Glitter Mail",
    hex: "0x7B",
    icon: "https://img.pokemondb.net/sprites/items/glitter-mail.png",
  },
  {
    value: 0x007c,
    label: "Mech Mail",
    hex: "0x7C",
    icon: "https://img.pokemondb.net/sprites/items/mech-mail.png",
  },
  {
    value: 0x007d,
    label: "Wood Mail",
    hex: "0x7D",
    icon: "https://img.pokemondb.net/sprites/items/wood-mail.png",
  },
  {
    value: 0x007e,
    label: "Wave Mail",
    hex: "0x7E",
    icon: "https://img.pokemondb.net/sprites/items/wave-mail.png",
  },
  {
    value: 0x007f,
    label: "Bead Mail",
    hex: "0x7F",
    icon: "https://img.pokemondb.net/sprites/items/bead-mail.png",
  },
  {
    value: 0x0080,
    label: "Shadow Mail",
    hex: "0x80",
    icon: "https://img.pokemondb.net/sprites/items/shadow-mail.png",
  },
  {
    value: 0x0081,
    label: "Tropic Mail",
    hex: "0x81",
    icon: "https://img.pokemondb.net/sprites/items/tropic-mail.png",
  },
  {
    value: 0x0082,
    label: "Dream Mail",
    hex: "0x82",
    icon: "https://img.pokemondb.net/sprites/items/dream-mail.png",
  },
  {
    value: 0x0083,
    label: "Fab Mail",
    hex: "0x83",
    icon: "https://img.pokemondb.net/sprites/items/fab-mail.png",
  },
  {
    value: 0x0084,
    label: "Retro Mail",
    hex: "0x84",
    icon: "https://img.pokemondb.net/sprites/items/retro-mail.png",
  },
  {
    value: 0x00b0,
    label: "Prism Scale",
    hex: "0xB0",
    icon: "https://img.pokemondb.net/sprites/items/cheri-berry.png",
  },
  {
    value: 0x00b1,
    label: "Sachet",
    hex: "0xB1",
    icon: "https://img.pokemondb.net/sprites/items/sachet.png",
  },
  {
    value: 0x00b2,
    label: "Whip Dream",
    hex: "0xB2",
    icon: "https://img.pokemondb.net/sprites/items/whip-dream.png",
  },
  {
    value: 0x00b3,
    label: "Bright Powder",
    hex: "0xB3",
    icon: "https://img.pokemondb.net/sprites/items/bright-powder.png",
  },
  {
    value: 0x00b4,
    label: "White Herb",
    hex: "0xB4",
    icon: "https://img.pokemondb.net/sprites/items/white-herb.png",
  },
  {
    value: 0x00b5,
    label: "Macho Brace",
    hex: "0xB5",
    icon: "https://img.pokemondb.net/sprites/items/macho-brace.png",
  },
  {
    value: 0x00b7,
    label: "Quick Claw",
    hex: "0xB7",
    icon: "https://img.pokemondb.net/sprites/items/quick-claw.png",
  },
  {
    value: 0x00b8,
    label: "Soothe Bell",
    hex: "0xB8",
    icon: "https://img.pokemondb.net/sprites/items/soothe-bell.png",
  },
  {
    value: 0x00b9,
    label: "Mental Herb",
    hex: "0xB9",
    icon: "https://img.pokemondb.net/sprites/items/mental-herb.png",
  },
  {
    value: 0x00ba,
    label: "Choice Band",
    hex: "0xBA",
    icon: "https://img.pokemondb.net/sprites/items/choice-band.png",
  },
  {
    value: 0x00bb,
    label: "Kings Rock",
    hex: "0xBB",
    icon: "https://img.pokemondb.net/sprites/items/kings-rock.png",
  },
  {
    value: 0x00bc,
    label: "Silver Powder",
    hex: "0xBC",
    icon: "https://img.pokemondb.net/sprites/items/silver-powder.png",
  },
  {
    value: 0x00bd,
    label: "Amulet Coin",
    hex: "0xBD",
    icon: "https://img.pokemondb.net/sprites/items/amulet-coin.png",
  },
  {
    value: 0x00be,
    label: "Cleanse Tag",
    hex: "0xBE",
    icon: "https://img.pokemondb.net/sprites/items/cleanse-tag.png",
  },
  {
    value: 0x00bf,
    label: "Soul Dew",
    hex: "0xBF",
    icon: "https://img.pokemondb.net/sprites/items/soul-dew.png",
  },
  {
    value: 0x00c0,
    label: "Deep Sea Tooth",
    hex: "0xC0",
    icon: "https://img.pokemondb.net/sprites/items/deep-sea-tooth.png",
  },
  {
    value: 0x00c1,
    label: "Deep Sea Scale",
    hex: "0xC1",
    icon: "https://img.pokemondb.net/sprites/items/deep-sea-scale.png",
  },
  {
    value: 0x00c2,
    label: "Smoke Ball",
    hex: "0xC2",
    icon: "https://img.pokemondb.net/sprites/items/smoke-ball.png",
  },
  {
    value: 0x00c3,
    label: "Everstone",
    hex: "0xC3",
    icon: "https://img.pokemondb.net/sprites/items/everstone.png",
  },
  {
    value: 0x00c4,
    label: "Focus Band",
    hex: "0xC4",
    icon: "https://img.pokemondb.net/sprites/items/focus-band.png",
  },
  {
    value: 0x00c5,
    label: "Lucky Egg",
    hex: "0xC5",
    icon: "https://img.pokemondb.net/sprites/items/lucky-egg.png",
  },
  {
    value: 0x00c6,
    label: "Scope Lens",
    hex: "0xC6",
    icon: "https://img.pokemondb.net/sprites/items/scope-lens.png",
  },
  {
    value: 0x00c7,
    label: "Metal Coat",
    hex: "0xC7",
    icon: "https://img.pokemondb.net/sprites/items/metal-coat.png",
  },
  {
    value: 0x00c8,
    label: "Leftovers",
    hex: "0xC8",
    icon: "https://img.pokemondb.net/sprites/items/leftovers.png",
  },
  {
    value: 0x00c9,
    label: "Dragon Scale",
    hex: "0xC9",
    icon: "https://img.pokemondb.net/sprites/items/dragon-scale.png",
  },
  {
    value: 0x00ca,
    label: "Light Ball",
    hex: "0xCA",
    icon: "https://img.pokemondb.net/sprites/items/light-ball.png",
  },
  {
    value: 0x00cb,
    label: "Soft Sand",
    hex: "0xCB",
    icon: "https://img.pokemondb.net/sprites/items/soft-sand.png",
  },
  {
    value: 0x00cc,
    label: "Hard Stone",
    hex: "0xCC",
    icon: "https://img.pokemondb.net/sprites/items/hard-stone.png",
  },
  {
    value: 0x00cd,
    label: "Miracle Seed",
    hex: "0xCD",
    icon: "https://img.pokemondb.net/sprites/items/miracle-seed.png",
  },
  {
    value: 0x00ce,
    label: "Black Glasses",
    hex: "0xCE",
    icon: "https://img.pokemondb.net/sprites/items/black-glasses.png",
  },
  {
    value: 0x00cf,
    label: "Black Belt",
    hex: "0xCF",
    icon: "https://img.pokemondb.net/sprites/items/black-belt.png",
  },
  {
    value: 0x00d0,
    label: "Magnet",
    hex: "0xD0",
    icon: "https://img.pokemondb.net/sprites/items/magnet.png",
  },
  {
    value: 0x00d1,
    label: "Mystic Water",
    hex: "0xD1",
    icon: "https://img.pokemondb.net/sprites/items/mystic-water.png",
  },
  {
    value: 0x00d2,
    label: "Sharp Beak",
    hex: "0xD2",
    icon: "https://img.pokemondb.net/sprites/items/sharp-beak.png",
  },
  {
    value: 0x00d3,
    label: "Poison Barb",
    hex: "0xD3",
    icon: "https://img.pokemondb.net/sprites/items/poison-barb.png",
  },
  {
    value: 0x00d4,
    label: "Never Melt Ice",
    hex: "0xD4",
    icon: "https://img.pokemondb.net/sprites/items/never-melt-ice.png",
  },
  {
    value: 0x00d5,
    label: "Spell Tag",
    hex: "0xD5",
    icon: "https://img.pokemondb.net/sprites/items/spell-tag.png",
  },
  {
    value: 0x00d6,
    label: "Twisted Spoon",
    hex: "0xD6",
    icon: "https://img.pokemondb.net/sprites/items/twisted-spoon.png",
  },
  {
    value: 0x00d7,
    label: "Charcoal",
    hex: "0xD7",
    icon: "https://img.pokemondb.net/sprites/items/charcoal.png",
  },
  {
    value: 0x00d8,
    label: "Dragon Fang",
    hex: "0xD8",
    icon: "https://img.pokemondb.net/sprites/items/dragon-fang.png",
  },
  {
    value: 0x00d9,
    label: "Silk Scarf",
    hex: "0xD9",
    icon: "https://img.pokemondb.net/sprites/items/silk-scarf.png",
  },
  {
    value: 0x00da,
    label: "Up-Grade",
    hex: "0xDA",
    icon: "https://img.pokemondb.net/sprites/items/up-grade.png",
  },
  {
    value: 0x00db,
    label: "Shell Bell",
    hex: "0xDB",
    icon: "https://img.pokemondb.net/sprites/items/shell-bell.png",
  },
  {
    value: 0x00dc,
    label: "Sea Incense",
    hex: "0xDC",
    icon: "https://img.pokemondb.net/sprites/items/sea-incense.png",
  },
  {
    value: 0x00dd,
    label: "Lax Incense",
    hex: "0xDD",
    icon: "https://img.pokemondb.net/sprites/items/lax-incense.png",
  },
  {
    value: 0x00de,
    label: "Lucky Punch",
    hex: "0xDE",
    icon: "https://img.pokemondb.net/sprites/items/lucky-punch.png",
  },
  {
    value: 0x00df,
    label: "Metal Powder",
    hex: "0xDF",
    icon: "https://img.pokemondb.net/sprites/items/metal-powder.png",
  },
  {
    value: 0x00e0,
    label: "Thick Club",
    hex: "0xE0",
    icon: "https://img.pokemondb.net/sprites/items/thick-club.png",
  },
  {
    value: 0x00e1,
    label: "Leek Stick",
    hex: "0xE1",
    icon: "https://img.pokemondb.net/sprites/items/stick.png",
  },
  {
    value: 0x00e2,
    label: "Strawberry Sweet",
    hex: "0xE2",
    icon: "https://img.pokemondb.net/sprites/items/strawberry-sweet.png",
  },
  {
    value: 0x00e3,
    label: "Berry Sweet",
    hex: "0xE3",
    icon: "https://img.pokemondb.net/sprites/items/berry-sweet.png",
  },
  {
    value: 0x00e4,
    label: "Love Sweet",
    hex: "0xE4",
    icon: "https://img.pokemondb.net/sprites/items/love-sweet.png",
  },
  {
    value: 0x00e5,
    label: "Clover Sweet",
    hex: "0xE5",
    icon: "https://img.pokemondb.net/sprites/items/clover-sweet.png",
  },
  {
    value: 0x00e6,
    label: "Flower Sweet",
    hex: "0xE6",
    icon: "https://img.pokemondb.net/sprites/items/flower-sweet.png",
  },
  {
    value: 0x00e7,
    label: "Ribbon Sweet",
    hex: "0xE7",
    icon: "https://img.pokemondb.net/sprites/items/ribbon-sweet.png",
  },
  {
    value: 0x00e8,
    label: "Star Sweet",
    hex: "0xE8",
    icon: "https://img.pokemondb.net/sprites/items/star-sweet.png",
  },
  {
    value: 0x00e9,
    label: "Sweet Apple",
    hex: "0xE9",
    icon: "https://img.pokemondb.net/sprites/items/sweet-apple.png",
  },
  {
    value: 0x00ea,
    label: "Tart Apple",
    hex: "0xEA",
    icon: "https://img.pokemondb.net/sprites/items/tart-apple.png",
  },
  {
    value: 0x00eb,
    label: "Cracked Pot",
    hex: "0xEB",
    icon: "https://img.pokemondb.net/sprites/items/cracked-pot.png",
  },
  {
    value: 0x00ec,
    label: "Chipped Pot",
    hex: "0xEC",
    icon: "https://img.pokemondb.net/sprites/items/chipped-pot.png",
  },
  {
    value: 0x00ed,
    label: "Galar Cuff",
    hex: "0xED",
    icon: "https://img.pokemondb.net/sprites/items/galar-cuff.png",
  },
  {
    value: 0x00ee,
    label: "Galar Crown",
    hex: "0xEE",
    icon: "https://img.pokemondb.net/sprites/items/galar-crown.png",
  },
  {
    value: 0x00fe,
    label: "Red Scarf",
    hex: "0xfe",
    icon: "https://img.pokemondb.net/sprites/items/red-scarf.png",
  },
  {
    value: 0x00ff,
    label: "Blue Scarf",
    hex: "0xff",
    icon: "https://img.pokemondb.net/sprites/items/blue-scarf.png",
  },
  {
    value: 0x0100,
    label: "Pink Scarf",
    hex: "0x100",
    icon: "https://img.pokemondb.net/sprites/items/pink-scarf.png",
  },
  {
    value: 0x0101,
    label: "Green Scarf",
    hex: "0x101",
    icon: "https://img.pokemondb.net/sprites/items/green-scarf.png",
  },
  {
    value: 0x0102,
    label: "Yellow Scarf",
    hex: "0x102",
    icon: "https://img.pokemondb.net/sprites/items/yellow-scarf.png",
  },
  {
    value: 0x0114,
    label: "Red Orb",
    hex: "0x114",
    icon: "https://img.pokemondb.net/sprites/items/red-orb.png",
  },
  {
    value: 0x0115,
    label: "Blue Orb",
    hex: "0x115",
    icon: "https://img.pokemondb.net/sprites/items/blue-orb.png",
  },
  {
    value: 0x011e,
    label: "Root Fossil",
    hex: "0x11e",
    icon: "https://img.pokemondb.net/sprites/items/root-fossil.png",
  },
  {
    value: 0x011f,
    label: "Claw Fossil",
    hex: "0x11f",
    icon: "https://img.pokemondb.net/sprites/items/claw-fossil.png",
  },
];

const BERRY_ITEM_OPTIONS = [{}];

const KEY_ITEM_OPTIONS = [
  {
    value: 0x00b6,
    label: "Exp Share",
    hex: "0xB6",
    icon: "https://img.pokemondb.net/sprites/items/exp-share.png",
  },
  {
    value: 0x0103,
    label: "Mach Bike",
    hex: "0x103",
    icon: "https://img.pokemondb.net/sprites/items/mach-bike.png",
  },
  {
    value: 0x0104,
    label: "Coin Case",
    hex: "0x104",
    icon: "https://img.pokemondb.net/sprites/items/coin-case.png",
  },
  {
    value: 0x0105,
    label: "Itemfinder",
    hex: "0x105",
    icon: "https://img.pokemondb.net/sprites/items/itemfinder.png",
  },
  {
    value: 0x0106,
    label: "Old Rod",
    hex: "0x106",
    icon: "https://img.pokemondb.net/sprites/items/old-rod.png",
  },
  {
    value: 0x0107,
    label: "Good Rod",
    hex: "0x107",
    icon: "https://img.pokemondb.net/sprites/items/good-rod.png",
  },
  {
    value: 0x0108,
    label: "Super Rod",
    hex: "0x108",
    icon: "https://img.pokemondb.net/sprites/items/super-rod.png",
  },
  {
    value: 0x0109,
    label: "S.S. Ticket",
    hex: "0x109",
    icon: "https://img.pokemondb.net/sprites/items/ss-ticket.png",
  },
  {
    value: 0x010a,
    label: "Contest Pass",
    hex: "0x10a",
    icon: "https://img.pokemondb.net/sprites/items/contest-pass.png",
  },
  {
    value: 0x010b,
    label: "Z-Power Ring",
    hex: "0x10b",
    icon: "https://img.pokemondb.net/sprites/items/z-power-ring.png",
  },
  {
    value: 0x010c,
    label: "Wailmer Pail",
    hex: "0x10c",
    icon: "https://img.pokemondb.net/sprites/items/wailmer-pail.png",
  },
  {
    value: 0x010d,
    label: "Devon Goods",
    hex: "0x10d",
    icon: "https://img.pokemondb.net/sprites/items/devon-goods.png",
  },
  {
    value: 0x010e,
    label: "Soot Sack",
    hex: "0x10e",
    icon: "https://img.pokemondb.net/sprites/items/soot-sack.png",
  },
  {
    value: 0x010f,
    label: "Basement Key",
    hex: "0x10f",
    icon: "https://img.pokemondb.net/sprites/items/basement-key.png",
  },
  {
    value: 0x0110,
    label: "Acro Bike",
    hex: "0x110",
    icon: "https://img.pokemondb.net/sprites/items/acro-bike.png",
  },
  {
    value: 0x0111,
    label: "Pokeblock Case",
    hex: "0x111",
    icon: "https://img.pokemondb.net/sprites/items/pokeblock-case.png",
  },
  {
    value: 0x0112,
    label: "Letter",
    hex: "0x112",
    icon: "https://img.pokemondb.net/sprites/items/letter.png",
  },
  {
    value: 0x0113,
    label: "Eon Ticket",
    hex: "0x113",
    icon: "https://img.pokemondb.net/sprites/items/eon-ticket.png",
  },
  {
    value: 0x0116,
    label: "Scanner",
    hex: "0x114",
    icon: "https://img.pokemondb.net/sprites/items/scanner.png",
  },
  {
    value: 0x0117,
    label: "Go-Goggles",
    hex: "0x117",
    icon: "https://img.pokemondb.net/sprites/items/go-goggles.png",
  },
  {
    value: 0x0118,
    label: "Meteorite",
    hex: "0x118",
    icon: "https://img.pokemondb.net/sprites/items/meteorite.png",
  },
  {
    value: 0x0119,
    label: "Room 1 Key",
    hex: "0x119",
    icon: "https://img.pokemondb.net/sprites/items/room-key.png",
  },
  {
    value: 0x011a,
    label: "Room 2 Key",
    hex: "0x11a",
    icon: "https://img.pokemondb.net/sprites/items/room-key.png",
  },
  {
    value: 0x011b,
    label: "Room 4 Key",
    hex: "0x11b",
    icon: "https://img.pokemondb.net/sprites/items/room-key.png",
  },
  {
    value: 0x011c,
    label: "Room 6 Key",
    hex: "0x11c",
    icon: "https://img.pokemondb.net/sprites/items/room-key.png",
  },
  {
    value: 0x011d,
    label: "Storage Key",
    hex: "0x11d",
    icon: "https://img.pokemondb.net/sprites/items/room-key.png",
  },
  {
    value: 0x0120,
    label: "Devon Scope",
    hex: "0x120",
    icon: "https://img.pokemondb.net/sprites/items/devon-scope.png",
  },
  {
    value: 0x015b,
    label: "Dynamax Band",
    hex: "0x15b",
    icon: "https://img.pokemondb.net/sprites/items/dynamax-band.png",
  },
  {
    value: 0x015c,
    label: "Gold Teeth",
    hex: "0x15c",
    icon: "https://img.pokemondb.net/sprites/items/gold-teeth.png",
  },
  {
    value: 0x015d,
    label: "Oak's Parcel",
    hex: "0x15d",
    icon: "https://img.pokemondb.net/sprites/items/oaks-parcel.png",
  },
  {
    value: 0x015e,
    label: "Poke Flute",
    hex: "0x15e",
    icon: "https://img.pokemondb.net/sprites/items/poke-flute.png",
  },
  {
    value: 0x015f,
    label: "Secret Key",
    hex: "0x15f",
    icon: "https://img.pokemondb.net/sprites/items/secret-key.png",
  },
  {
    value: 0x0160,
    label: "Bike Voucher",
    hex: "0x160",
    icon: "https://img.pokemondb.net/sprites/items/bike-voucher.png",
  },
  {
    value: 0x0161,
    label: "Mega Ring",
    hex: "0x161",
    icon: "https://img.pokemondb.net/sprites/items/mega-ring.png",
  },
  {
    value: 0x0162,
    label: "Old Amber",
    hex: "0x162",
    icon: "https://img.pokemondb.net/sprites/items/old-amber.png",
  },
  {
    value: 0x0163,
    label: "Card Key",
    hex: "0x163",
    icon: "https://img.pokemondb.net/sprites/items/room-key.png",
  },
  {
    value: 0x0164,
    label: "Lift Key",
    hex: "0x164",
    icon: "https://img.pokemondb.net/sprites/items/lift-key.png",
  },
  {
    value: 0x0165,
    label: "Helix Fossil",
    hex: "0x165",
    icon: "https://img.pokemondb.net/sprites/items/helix-fossil.png",
  },
  {
    value: 0x0166,
    label: "Dome Fossil",
    hex: "0x166",
    icon: "https://img.pokemondb.net/sprites/items/dome-fossil.png",
  },
  {
    value: 0x0167,
    label: "Silph Scope",
    hex: "0x167",
    icon: "https://img.pokemondb.net/sprites/items/silph-scope.png",
  },
  {
    value: 0x0168,
    label: "Bicycle",
    hex: "0x168",
    icon: "https://img.pokemondb.net/sprites/items/bicycle.png",
  },
  {
    value: 0x0169,
    label: "Town Map",
    hex: "0x169",
    icon: "https://img.pokemondb.net/sprites/items/town-map.png",
  },
  {
    value: 0x016a,
    label: "Stat Scanner",
    hex: "0x16a",
    icon: "https://img.pokemondb.net/sprites/items/stat-scanner.png",
  },
  {
    value: 0x016b,
    label: "Poke Rider",
    hex: "0x16b",
    icon: "https://img.pokemondb.net/sprites/items/fame-checker.png",
  },
  {
    value: 0x016c,
    label: "TM Case",
    hex: "0x16c",
    icon: "https://img.pokemondb.net/sprites/items/tm-case.png",
  },
  {
    value: 0x016d,
    label: "Berry Pouch",
    hex: "0x16d",
    icon: "https://img.pokemondb.net/sprites/items/berry-pouch.png",
  },
  {
    value: 0x016e,
    label: "Teachy TV",
    hex: "0x16e",
    icon: "https://img.pokemondb.net/sprites/items/teachy-tv.png",
  },
  {
    value: 0x016f,
    label: "Tri-Pass",
    hex: "0x16f",
    icon: "https://img.pokemondb.net/sprites/items/tri-pass.png",
  },
  {
    value: 0x0170,
    label: "Rainbow Pass",
    hex: "0x170",
    icon: "https://img.pokemondb.net/sprites/items/rainbow-pass.png",
  },
  {
    value: 0x0171,
    label: "Tea",
    hex: "0x171",
    icon: "https://img.pokemondb.net/sprites/items/tea.png",
  },
  {
    value: 0x0172,
    label: "Mystic Ticket",
    hex: "0x172",
    icon: "https://img.pokemondb.net/sprites/items/mystic-ticket.png",
  },
  {
    value: 0x0173,
    label: "Aurora Ticket",
    hex: "0x173",
    icon: "https://img.pokemondb.net/sprites/items/aurora-ticket.png",
  },
  {
    value: 0x0174,
    label: "Locater",
    hex: "0x174",
    icon: "https://img.pokemondb.net/sprites/items/vs-seeker.png",
  },
  {
    value: 0x0175,
    label: "Ruby",
    hex: "0x175",
    icon: "https://img.pokemondb.net/sprites/items/ruby.png",
  },
  {
    value: 0x0176,
    label: "Sapphire",
    hex: "0x176",
    icon: "https://img.pokemondb.net/sprites/items/sapphire.png",
  },
];

// 0x2ff seems beyond what the game allows
